server:
  port: 8090

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: echoes.capd@gmail.com
    password: cflvaxvmifbkjxbi
    email: echoes.capd@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000

logging:
  level:
    org.springframework.security: DEBUG